### ISSUE TITLE
Bridge addChannel options

### ISSUE THREAD

**Issue by danofa** [CyCoreSystems/ari#100]
Hi,

I'm having trouble trying to add a channel to a bridge and specify "absorbDTMF" as per [the official docs](https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Bridges+REST+API#Asterisk16BridgesRESTAPI-addChannel), is it possible with this library ?

Many thanks

**Comment by Ulexus** [comment]
Aha, I hadn't realized those had been incorporated in the API.  I'll need to regenerate the models.

**Comment by Ulexus** [comment]
Since this change breaks the `ari.Bridge` interface compatibility (due to adding the new AddChannelWithOptions function), it requires a major version change.  I'll need to run a few more thorough tests and update some other dependencies before I can release it, but feel free to test against master or v5.0.0-pre1, in the mean time.
