### ISSUE TITLE
Hangup a channel does not work

### ISSUE THREAD

**Issue by ehsanrocket** [CyCoreSystems/ari#98]
hi all 
I have created a channel in a.go :
```go
key := ari.Key{Kind: ari.ChannelKey, Node: "caller", App: "xx"}
org := ari.OriginateRequest{Endpoint: "SIP/x", App: "xx", CallerID: "test" , Timeout: 300}
t1, err := cl.Channel().StageOriginate(&key, org)
	if err != nil {
		fmt.Print("Cannot create channel : ", err)
	}
t1.Exec()
```
now in b.go I want to destroy the channel so I do the following :
```go
key := ari.Key{ari.ChannelKey, "01d5sgk517qws4rsa91v5tzf3r-ch" ,"caller", " ", App: "xx"}
cl.Channel.Hangup(&key, "for test")
```
but it does not Hangup the channel
is there any way to destroy a channel like :

```sh
curl -s -u ehsan:esx -X  DELETE "http://localhost:8088/ari/channels/01d5sgk517qws4rsa91v5tzf3r-ch"
```

**Comment by Ulexus** [comment]
`c.Hangup()` should be calling exactly that HTTP request, under the hood.

If you look at [channel.go](https://github.com/CyCoreSystems/ari/blob/master/client/native/channel.go#L51), you will see that it is using the delete operation on the `x/channels/{channelID}` URI.

I would suspect your problem lies elsewhere.

In general, you would not want to manually construct the `ari.Key`s.  This is what Handles (such as Channel Handles) are for.  You can pass channel handles around in local code, and they contain references to the client, the app, subscriptions, etc.  You can pass `ari.Key`s around over a network, either as JSON or as protobufs, and they contain everything needed for another client to reconstruct the Handle.  See the example applications for common usage.

**Comment by Ulexus** [comment]
Also, in your example, please note that your original Key will NOT match the key returned from the Originate.  The Key which is passed to Originate (or StageOriginate) is a reference Key.  It is completely optional and only used for matching the new channel to an existing channel, in terms of Node (the Asterisk box on which the channel should reside), and communication parameters, such as codecs.

**Comment by Ulexus** [comment]
Also reference: [https://github.com/CyCoreSystems/ari#handles](https://github.com/CyCoreSystems/ari#handles).  The non-standard Hangup code you are using _may_ be causing the problem.

**Comment by ehsanrocket** [comment]
thank you 
yes I should use channel handles. I use channel.Get() to get the ChannelHandle of the channel
and it works
```
key := ari.Key{"channel", "01d5sn4kqckph8gj33t7qk5fee-ch", "", "", "xx"}
tt := cl.Channel().Get(&key)
tt.Hangup()
```
but I wonder why this method works for bridge
```
bkey := ari.Key{ari.BridgeKey, bid, "", "", "ss"}
cl.Bridge.Delete(&bkey)
```
also works by BridgeHandle
```
bkey := ari.Key{ari.BridgeKey, bid, "", "", "ss"}
b := cl.Bridge.Get(&bkey)
b.Delete()
```

**Comment by Ulexus** [comment]
Asterisk is picky about the hangup codes.  When you use the Hangup() from the ChannelHandle, it uses a standard hangup code.  The one you are using in your example is not a standard code.  I would guess that Asterisk is ignoring it, or otherwise not processing it properly.  It may be translating it into something which your SIP stack or endpoint is not recognizing.  It's hard to say without more information.

**Comment by ehsanrocket** [comment]
yes, when I use ChannelHandles and BridgeHandles to hangup a channel or delete a bridge it works correctly.
but for Bridges, it also works even when I do not use BridgeHandle

**Comment by Ulexus** [comment]
Bridges are just deleted, not hung up.  There are no hangup codes to be transmitted for a bridge, which is why they work for you in this manner.

**Comment by ehsanrocket** [comment]
Yeah I got it.
Thank you Ulexus 🙏
